### ISSUE TITLE
Shopify Mobile does not provide working alternative for Contextual Save Bar, cannot perform actions in Shopify Mobile on such page

### ISSUE THREAD

**Issue by excitexcite** [Shopify/shopify-app-bridge#330] opened 2024-04-03 11:45 UTC
## Describe the bug

Unable to perform save/cancel actions in Shopify Mobile andoird app. For these actions for browser version I use Contextual Save Bar. The tick and the cross are shown instead of contextual save bar in Shopify Mobile, but they do nothing.

### To Reproduce

Steps to reproduce the behaviour:

1. Launch Shopify Mobile for android
2. Open your embeded app
3. Open the page, where you use Contextual Save Bar for performing actions (to save an entity for example).
4. Click tick/cross
5. Nothing happens, no action perfromed.

![appbridge-android](https://github.com/Shopify/shopify-app-bridge/assets/56977515/ba42fda0-88f3-41bd-aaf7-60b7569c8b89)

### Expected behaviour

Shopify guidelines encourage us to use shopify app bridge components, so I expect to have something like contextual save bar in shopify android app, or at least have the tick and the cross icons working.

### Packages and versions

Using latest version of shopify-app-bridge via CDN.

## Platform

- OS: [Android]
- OS Version: 9 PKQ1.190319.001
- App:  Shopify Mobile

**Comment by darrynten** [comment] 2024-04-18 06:24
This is still a serious problem, the save and discard buttons in Shopify Mobile do nothing

**Comment by darrynten** [comment] 2024-04-22 05:33
@autoserve this will probably take a long time to get fixed.

We've decided to block access to any functionality that uses the save bar on shopify mobile with a message directing users to the desktop or mobile web version until it is resolved.

**Comment by darrynten** [comment] 2024-05-02 05:18
@henrytao-me is there any progress on this?

**Comment by darrynten** [comment] 2024-05-07 09:53
@henrytao-me any progress on this?

All of the App Bridge 4.x versions of our apps are currently stuck in QA since none of them can save anything on Shopify Mobile.

It's been like this for over 2 months now, should our team be looking at implementing something like auto-saving every time the user changes the value and doing away with the save bar altogether, or is this issue really being addressed internally with a realistic deadline?

**Comment by henrytao-me** [comment] 2024-05-08 13:23
The team is looking into this. I will give you an update by end of day.

**Closed** 2024-05-08 20:32 UTC
Labels: bug

**Comment by henrytao-me** [comment] 2024-05-08 20:44
It's fixed on production.

**Comment by darrynten** [comment] 2024-05-09 04:38
I can confirm it's working again, thank you from all of us!
