### ISSUE TITLE
Documentation for using @shopify/app-bridge-host on a local env

### ISSUE THREAD

**Issue by ctrlaltdylan** [Shopify/shopify-app-bridge#14] opened 2020-10-07 18:07 UTC
### Describe the feature you’d like

As a partner, I'd like to develop faster locally without having to rely on an ngrok tunnel + an actual Shopify app.

The app-bridge-host looks like it was designed to mock the Shopify dash somewhat, which would allow developers to work faster with dramatically shorter wait times.

### Describe alternatives you've considered

Can figure it out on my own I guess.

### Additional context

Conversation in Slack: https://shopifypartners.slack.com/archives/CKK8FHFDF/p1602087862014500

**Comment by iainmcampbell** [comment] 2020-10-15 14:53
closing this as a duplicate of #12, you were beaten by 20 minutes ;)

**Closed by iainmcampbell** 2020-10-15 14:53 UTC

**Comment by ctrlaltdylan** [comment] 2020-10-15 14:54
@iainmcampbell I'm always late to the party 😂
