### ISSUE TITLE
Partner Dashboard missing Admin Performance data

### ISSUE THREAD

**Issue by fairknowe** [Shopify/shopify-app-bridge#253] opened 2023-11-22 16:56 UTC
## Describe the bug

The last date admin performance data for my app appeared was Nov 6. I understand this was due to a bug that was apparently fixed, but I am still not getting data. I haven't found any solutions in existing issues or in the Partner Community forums.

<img width="941" alt="Admin Performance data missing" src="https://github.com/Shopify/shopify-app-bridge/assets/13555618/587047a2-6f88-428a-98d8-6263d1a4c03e">

### Packages and versions
`@shopify/app-bridge @ 3.7.9` is loaded by `<script src="https://unpkg.com/@shopify/app-bridge@3" nonce="<%= request.content_security_policy_nonce %>"></script>` in my app/views/layouts/authenticated.html.erb file.
`shopify_app (21.7.0) and shopify_api (13.3.0)` are loaded as Gems

## Platform

- OS: MacOS, Windows
- OS Version: 13.6.1
- App: Admin embedded

### Additional context

I'm using Rails 7.1
I am not using React on the front-end. Instead I'm using a vanilla HTML with CSS/Polaris stying, and Hotwire.

My App is still under development and is being loaded only in development stores.

**Comment by daviareias** [comment] 2024-01-26 15:39
#273 

I've been complaining about this to support for the past 6 months and there's no solution, just keep sending message to support until they fix it.

**Comment by fairknowe** [comment] 2024-01-26 21:46
### Update
I now load app-bridge (v4?) by:

> ` <meta name="shopify-api-key" content="<%= ShopifyApp.configuration.api_key %>">`

> `<script src="https://cdn.shopify.com/shopifycloud/app-bridge.js" nonce="<%= request.content_security_policy_nonce %>">`
> `</script>`

The shopify_app gem is now at v (21.10.0).

I still don't have **any** APP Admin performance stats in my dev stores.

**Comment by neoanic** [comment] 2024-02-22 21:11
I've encountered a similar issue where the performance metrics are no longer reported in the admin performance dashboards after switching to the CDN version of App Bridge last December. I'm using Next.js 14, the latest version of React, and Shopify version 2024-01. Interestingly, while the App Bridge performance metrics have ceased, my Vercel Speed Insights are functioning normally.

Has there been any progress on this issue, or could anyone provide insights into potential workarounds? This is particularly critical as I am in the process of preparing my app for review.

**Comment by neoanic** [comment] 2024-03-13 16:52
![CleanShot 2024-03-13 at 17 50 51@2x](https://github.com/Shopify/shopify-app-bridge/assets/56780243/0177f73e-62b0-4bcc-863c-3e0eabbd15c8)

Any updates on this issue? I still don't have any performance statistics in the partner dashboard. 
Using the latest App Bridge (CDN Version)

**Comment by neoanic** [comment] 2024-03-18 17:56
Update: Three days ago, we successfully published our app. As of today, I've observed that the performance data is accessible once more. It's unclear whether this improvement is due to changes within the app bridge or if it's a direct consequence of the app's publication.

**Comment by henrytao-me** [comment] 2024-03-21 18:58
@fairknowe @neoanic we just pushed a fix in App Bridge CDN. May I have your appId to try it out? Action items:
- From our team:
  + Have your appIds to turn on the new fix
- From your team:
  + Make sure you have App Bridge CDN in your app. No other action required

**Comment by henrytao-me** [comment] 2024-03-22 15:01
@JoaoGabrielAlves I can see your dashboard is empty while the webVitals events do send to the server. I am investigating right now. Are you okay to opt-in to a new WebVitals fix?

**Comment by henrytao-me** [comment] 2024-03-25 19:27
@JoaoGabrielAlves I confirmed the issue and forwarded to data team to investigate. I will keep you posted about missing performance metrics.

**Comment by JoaoGabrielAlves** [comment] 2024-03-25 20:48
Thank you @henrytao-me !

**Comment by scart88** [comment] 2024-03-30 01:09
We have been experiencing the same issue for the past week. 

It looks like the problem was fixed today. We have missing data between March 23 and March 28

Anyway, I'm glad the issue is fixed now.

**Closed as completed** 2024-04-24 17:35 UTC
Labels: bug

**Comment by daviareias** [comment] 2024-04-25 06:54
>     * Apps that have less than 100 load times per month won't have BFS badge.

This is not true, you need at least 1000 loads per month in my calculation, because app bridge is not recording most of sessions.

We had 200 installations last month and you can see there's a huge disparity between FID and LCP recording:
![Screen Shot 2024-04-25 at 14 45 59](https://github.com/Shopify/shopify-app-bridge/assets/83703256/888c7cc7-5b12-4da1-a92e-db4cfd4be27a)
![Screen Shot 2024-04-25 at 14 49 38](https://github.com/Shopify/shopify-app-bridge/assets/83703256/19e79ba1-3b71-421f-bd8c-5fcf2273d0a7)
![Screen Shot 2024-04-25 at 14 50 06](https://github.com/Shopify/shopify-app-bridge/assets/83703256/f79474d2-bb1c-4830-a12f-f2b7fcd09d03)
![Screen Shot 2024-04-25 at 14 53 57](https://github.com/Shopify/shopify-app-bridge/assets/83703256/24ebb7ba-6c89-4701-aae7-da8c08ceac29)
![Screen Shot 2024-04-25 at 14 54 04](https://github.com/Shopify/shopify-app-bridge/assets/83703256/48a5bb11-1d3d-4115-a68b-9c25e14c24c5)

**Comment by wissem** [comment] 2024-06-04 07:42
hey @henrytao-me, we are also running into a similar issue. We are moving from a standalone app to an embedded app, we use `@shopify/app-bridge-react` version 3.7.7 and react 18. 
There are no web-vitals error on the console. Nothing is being reported under Admin Performance (LCP, CLS, FID are all empty.) We have waited for a few weeks now and have been openning the app multiple times per day.

My testing App ID: 5005323
Could you please have a look?

**Comment by daviareias** [comment] 2025-02-19 12:11
> Hey [@daviareias](https://github.com/daviareias), did you ever find a workaround? Our app also misses a lot of sessions on the partners dashboard compared to what we can mesure directly in the browser JS console using web-vitals.

No, I never found any workaround this. I can't believe apps with 5 ~ 10 reviews are getting 1000+ sessions so I'm pretty sure they are either using fake sessions or their apps are so bad that they the user has to keep coming back to their interface to keep the app working.
