### ISSUE TITLE
Shopify POS 6.42.0 for iOS has broken multiple things across App Bridge POS

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#50] opened 2021-05-08 20:58 UTC
~1. Camera barcode scanner no longer returns payload using previous subscribe method; the scanner itself also looks different (no red line in middle)~
2. **`localStorage` no longer works** - I really hope this is a bug / oversight and not a design decision. My apps cache authorization and other merchant configuration properties using `localStorage.setItem()` on the initial load and then pull this data using `localStorage.getItem()` on subsequent opens to speed up the load. `localStorage` previously was cleared when Shopify POS was restarted - this was desirable behavior. Embedded app load time is one of the primary complaints I get about my app, and removing `localStorage` will only exacerbate this.
3. **`pos.device.serialNumber` is gone. `device` in `app.getState().then((pos)` is now an empty json {}. I critically need `serialNumber`**, or some static device ID provided by Shopify, in order to identify the terminal as my app interfaces with hardware and the hardware needs to know which POS terminal it's talking to. And now with `localStorage` broken, there's currently no manual workaround I can employ. 
4. **I can't debug anything in Mac Console anymore using the bottom method**: https://shopify.dev/tutorials/debug-your-app-with-shopify-app-bridge. Now it only shows [this](https://photos.app.goo.gl/u8X1ueJKBhAkPze77) with no subsequent logging. Previously as soon as the app loaded it would show all of [this] and I'd be able to debug as well (https://photos.app.goo.gl/rCUnQGW8bGHaMGey7).

Other, not specific to my apps: 
1. There is a noticeable latency when tapping on a tile on the home screen with longer embedded app load times in general 
2. I have experienced random crashes, this appears to be the stacktrace: `Attempt to present <UIAlertController: 0x10b822200> on <AppBridge.EmbeddedAppViewController: 0x106d872b0> (from <AppBridge.EmbeddedAppViewController: 0x106d872b0>) whose view is not in the window hierarchy.`

Please prioritize these fixes - I've invested a good portion of the last year building plugins for Shopify POS and this one update this has effectively broken a lot of key functionality across my apps. Thank you.

**Comment by derrickrc** [comment] 2021-05-08 22:40
@andrewapperley has fixed barcode scanner issue:

`scanner.subscribe(Scanner.Action.CAPTURE, function (payload) {` becomes `app.subscribe(Scanner.ActionType.CAPTURE, function (payload) {`

**Comment by conraddecker** [comment] 2021-05-11 22:44
I'm seeing some issues as well and just curious if the fix for these will be released as a POS update or in some other manner behind the scenes. I'd like to let our staff know what to expect as well as when they can expect it to return to normal. As of right now, I'm still seeing issues.

I'm sure you're aware but this is the second time in only a few weeks that an update to the Shopify POS app has broken embedded app / app bridge functionality. Previously you broke your own Order Printer app and left us without that functionality for several days. This time around you've broken our internal loyalty program that runs using App Bridge. While both aren't necessarily mission critical, we do rely on them heavily for providing a positive consumer experience as well as for running internal operations.

**Comment by derrickrc** [comment] 2021-05-12 15:25
Looks like 6.42.1 was released yesterday and it resolves these issues. Thanks @andrewapperley!

**Comment by conraddecker** [comment] 2021-05-12 15:26
Can confirm as well. Updated this morning and everything seems to be back to normal. Thanks for moving quickly on a fix.

**Comment by derrickrc** [comment] 2021-05-12 15:43
@charles-tyler I'm not sure, but it might be possible... @andrewapperley sounds like maybe a reversion needs to happen for standard Shopify app as well?

**Comment by charles-tyler** [comment] 2021-05-13 15:50
Any updates on this @andrewapperley ? The code above doesn't seem to help. Thanks

**Comment by pramodparanthaman** [comment] 2021-05-18 14:48
Here's what I did to to get this to work on iOS (tested on Shopify POS and Mobile), this is still broken in the new Android Shopify POS app #52.

The old API was allowing the code to check for features with every barcode scan call with no issues. Now, I check only once or it doesn't work. Also, the format of the barcode payload is different under different APIs.

scanner.js - scanBarcode() sends the barcode to the callback function
```
import {Features, Group, Scanner, Toast} from '@shopify/app-bridge/actions';
var subscribed = false;
var available = false;
var scanner = null;
var features = null;
export const scanBarcode = (app, barcodeCallback) => {
  try {
    // Open camera scanner
    if(available) {  // Already checked for scanner and found available
      scanner.dispatch(Scanner.Action.OPEN_CAMERA)
    } else { // Check for scanner only once
      scanner = Scanner.create(app);
      features = Features.create(app);
      features.subscribe(Features.Action.REQUEST_UPDATE, function (payload) {
        if (payload && payload.feature && payload.feature[Scanner.Action.OPEN_CAMERA]) {
          available = payload.feature[Scanner.Action.OPEN_CAMERA].Dispatch;
          if (available) {
            scanner.dispatch(Scanner.Action.OPEN_CAMERA)
          }
        }
      });
    }
    // Subscribe to scan capture event
    if(!subscribed) { // Do not subscribe more than once
      subscribed = true;
      app.subscribe(Scanner.ActionType.CAPTURE, payload => { // payload format is different on different APIs
        const barcode = payload.data.data ? payload.data.data : payload.data.scanData;
        barcodeCallback(barcode);
      });
      // Dispatch an action to request camera scanner permission
      features.dispatch(Features.Action.REQUEST, {
        feature: Group.Scanner,
        action: Scanner.Action.OPEN_CAMERA
      });
    }
  } catch (err) {
    console.log(err);
    alert("Camera scanner not available.");
  }                
};
```

**Comment by marco-visualsquares** [comment] 2021-05-26 10:34
Up to now, there isn't a worked version for both android and IOS. I tried using both appBridge v1 and v2, but seems there are some breaking changes and lack of proper documentations of app bridge v2, I don't think is v2 is ready for it yet.
```const barcode = payload.data.data ? payload.data.data : payload.data.scanData;```
It is really unacceptable to see API having different payload format. while @pramodparanthaman solution may be a temporary help, it's shopify team's responsibility to fix it on their side. It has been days since the issue happened but still no proper fix yet. Really disappointed to this big update

**Comment by derrickrc** [comment] 2021-06-14 15:09
+1  @andrewapperley this is the issue I was describing last week and where I tried to send you the Mac Console logs. I am hearing this from multiple merchants (who are distressed) as the app technically "works" but it is causing Shopify POS to crash. It doesn't happen every single time so it's been difficult to troubleshoot, but for some merchants it's happening on every single scan.

**Comment by pramodparanthaman** [comment] 2021-06-15 09:05
@andrewapperley I updated my iPad to the latest Shopify POS 6.47.0 app released today.
I scanned around 20 products with no problems. The app-bridge scanner crash issue appears to be fixed now.
Thank you!

What's going on with Shopify POS on Android? Scanning is still broken #52. Can you please ping the Android team.

**Comment by nikevp** [comment] 2021-06-16 04:38
Like @pramodparanthaman, I can confirm 6.47.0 resolved scanning issues for my application. It was so much fun trying to debug this over the weekend with no error logs 😆

**Closed** 2021-06-21 17:55 UTC
Labels: bug
