### ISSUE TITLE
App bridge is not measuring First Input Delay

### ISSUE THREAD

**Issue by daviareias** [Shopify/shopify-app-bridge#273] opened 2024-01-21 16:46 UTC
## Describe the bug

AppBridge is not correctly measuring the 'First Input Delay' (FID) metric for web vital sessions. This discrepancy in the web vitals measurement is affecting our app's 'Built for Shopify' status, as the platform requires at least 100 web vital sessions to be recorded. 

It's been observed that Shopify is capturing up to 7 times more 'Largest Contentful Paint' (LCP) sessions compared to FID, which suggests a potential bug in the FID tracking or a misconfiguration.

This is inconsistent with the 'Built for Shopify' status requirement, which stipulates achieving 50 active installations at any given time. The current discrepancy suggests that to meet the erroneous 100 session requirement, an app would need to maintain a much higher installation rate, potentially around 100 installations per month. This rate is disproportionately high and approximately 20 times greater than the actual 'Built for Shopify' requirement.

### To Reproduce

Steps to reproduce the behaviour are not applicable as the issue lies in AppBridge and Shopify Partner dashboard's internal metrics collection mechanism.

Attached is a screenshot showing the disparity in the 'Largest Contentful Paint' and 'First Input Delay' measurements.
![Screen Shot 2024-01-22 at 00 30 18](https://github.com/Shopify/shopify-app-bridge/assets/83703256/e7a1c2ff-5389-4348-b596-842c742846b6)

Here's the warning in the Shopify partner's dashboard saying we don't meet requirements because there are not enough sessions, even though our FID was never below the required measure (if we were we would never get the badge in the first place):
![Screen Shot 2024-01-22 at 11 35 13](https://github.com/Shopify/shopify-app-bridge/assets/83703256/fdebf80b-c0ee-480b-b72a-b3cf46b3e6a4)
![Screen Shot 2024-01-22 at 11 35 22](https://github.com/Shopify/shopify-app-bridge/assets/83703256/a7acb2f3-c323-464b-a024-246a4a9aacd3)

### Expected behaviour

We expect AppBridge to accurately measure all web vital metrics, including 'First Input Delay', to ensure that our app meets the necessary performance standards for maintaining our 'Built for Shopify' status.

### Packages and versions

- `@shopify/app-bridge cdn version (https://cdn.shopify.com/shopifycloud/app-bridge.js)`
- `@shopify/polaris` @ `^12.0.0`

## Platform

- OS: MacOS, Windows, iOS, Android
- OS Version: N/A
- App: Shopify Mobile, Shopify POS, Chrome, Safari, Firefox

### Additional context

The app’s configuration is standard and follows Shopify's recommended setup with Node and Next.js for the backend. This measurement inconsistency has first been noticed 6 months ago and it already affected one of our apps, it will soon affect another app within around 10 days, unless we pump up those numbers.

```[tasklist]
### Tasks
```

**Comment by Stef733** [comment] 2024-01-22 02:01
I second that, are we expected to have 100 loads daily to get a measurement?

**Comment by daviareias** [comment] 2024-02-21 02:54
Third time this happened this year:

![Screen Shot 2024-02-21 at 10 52 53](https://github.com/Shopify/shopify-app-bridge/assets/83703256/3fa57eca-d15c-42cc-9858-cc023d254861)
![Screen Shot 2024-02-21 at 10 53 55](https://github.com/Shopify/shopify-app-bridge/assets/83703256/eca89967-a59d-48c5-8c6d-db8a5d104653)

**Comment by henrytao-me** [comment] 2024-04-01 13:40
FID relies on user input. I confirmed that it is reported properly. So, I close this ticket for now. Feel free to reopen or comment your appId so I can take a look. 

Note that: there is an ongoing issue about missing all metrics in partner dashboard due to data pipeline issue which is being investigated here https://github.com/Shopify/shopify-app-bridge/issues/253

**Closed by henrytao-me** 2024-04-01 13:40 UTC
Labels: bug

**Comment by daviareias** [comment] 2024-05-10 08:58
Not sure how to solve this. Should we keep emailing the users to keep loading the app for no reason?

Should we abandon "app extensions" to force users to load the app instead to hit this metric?

![Screenshot 2024-05-10 at 2 34 50 PM](https://github.com/Shopify/shopify-app-bridge/assets/83703256/881cc047-cb95-4a7a-9f3f-4903caefbd73)
![Screenshot 2024-05-10 at 2 21 22 PM](https://github.com/Shopify/shopify-app-bridge/assets/83703256/d219e202-99e7-4ab1-bf79-f02007ab61d1)
![Screenshot 2024-05-10 at 2 21 01 PM](https://github.com/Shopify/shopify-app-bridge/assets/83703256/869f8e7a-91c5-4348-a0a1-9f763dc6c432)

**Comment by dev-coderise** [comment] 2024-05-30 00:20
> Note that: there is an ongoing issue about missing all metrics in partner dashboard due to data pipeline issue which is being investigated here #253

We noticed that our FID is missing some days as well. For example, you can see it skipped May 24 in screenshot below:
<img width="169" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/57698491/10e1b4ea-a9b5-4ebc-86cd-68f9b3540070">

but CLS included May 24 data and also reports almost 2x more loads i.e.
<img width="167" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/57698491/add29fc4-a24a-4974-b6bb-22a700483149">

Due to the  100 FID load requirement, we are not able to submit the app for BFS badge even though we fulfill other requirements i.e.
<img width="613" alt="image" src="https://github.com/Shopify/shopify-app-bridge/assets/57698491/4a945f99-088d-40ec-9679-7d600b4fb7e9">

Can someone explain why CLS loads are different than FID loads? 

If Shopify is missing some metrics, shouldn't this 100 FID load requirement be waived?

Also, this requirement seems like an anti-pattern. Ideally, in today's automation world, the best apps are those that you set once and they automatically run in the background forever without any further manual interactions. So, on one hand, the BLS badge is trying to follow best standards, but at the same time, penalizing app developers by imposing some load requirement which does not make too much sense to me as a developer.

**Comment by danielristic** [comment] 2025-07-24 15:24
Not sure why this and https://github.com/Shopify/shopify-app-bridge/issues/253 have been closed as this is still a major problem for partners. It also creates an incentive to constantly refresh apps just to get enough recorded loads as most get missed. If you're going to force common metrics on everyone at least make sure they actually work.

**Comment by daviareias** [comment] 2025-07-24 17:42
> Not sure why this and [#253](https://github.com/Shopify/shopify-app-bridge/issues/253) have been closed as this is still a major problem for partners. It also creates an incentive to constantly refresh apps just to get enough recorded loads as most get missed. If you're going to force common metrics on everyone at least make sure they actually work.

I've tried refreshing my app 60 times using brave browser and didn't see to record a session. I have no idea how their system gets triggered.

**Comment by coderiseio** [comment] 2025-07-24 18:17
Follow-up: We spent almost 6 months to improve our app based on "Built for Shopify" guidelines but finally gave up as we couldn't meet their required INS load requirement even though are app is very well built. 

<img width="1062" height="837" alt="Image" src="https://github.com/user-attachments/assets/bb3c829f-8aa3-4af7-a206-90f07a8856bd" />
