### ISSUE TITLE
App bridge reloads app multiple times on first open

### ISSUE THREAD

**Issue by quard8** [Shopify/shopify-app-bridge#265] opened 2024-01-03 23:32 UTC
## Describe the bug

I started debugging my LCP score and found out that app loading twice. Because of that all JS code started loading multiple times and I guess LCP score impacted. 

I checked "Search and Discovery" app and found same behaviour. On app without App Bridge from CDN everything working as expected. 

I found that App Bridge script send messages "APP::NAVIGATION::HISTORY::REPLACE" to host and looks like this is reason to reload entire app. 

<img width="984" alt="Screenshot 2024-01-04 at 00 55 11" src="https://github.com/Shopify/shopify-app-bridge/assets/318700/f26109b4-2813-4bfc-94e9-3cd25dd5c29d">

Code from minified script:

```js
"./navigation.ts": ({protocol: t})=>{
            const n = self.navigation;
            function e(n, e) {
                if (!n)
                    return;
                const o = f(new URL(n,location.href))
                  , i = `${o.pathname}${o.search}${o.hash}`;
                l && t.send("Navigation.history." + e, {
                    path: i
                })
            }
```

`l` is always true because of `l = window.name.startsWith("app-iframe")` 

### To Reproduce

Steps to reproduce the behaviour:

1. Launch the "Search and Discovery" app
2. See network tab with multiple loads of the app

<img width="1224" alt="Screenshot 2024-01-04 at 01 22 33" src="https://github.com/Shopify/shopify-app-bridge/assets/318700/50826367-5ad9-4a06-8323-74addf7b64d2">
<img width="1205" alt="Screenshot 2024-01-04 at 01 22 37" src="https://github.com/Shopify/shopify-app-bridge/assets/318700/08811318-ede8-4a38-9ebe-eccc60034ef7">

### Expected behaviour

Embedded app loads once

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

- App Bridge from CDN

## Platform

- OS: MacOS
- OS Version: OSX Sonoma 14.2.1
- App: Chrome, Safari

**Comment by kyakaze** [comment] 2024-01-29 10:38
Yea we got this same issue, the app sends request twice, the first is cancelled, but our server already processes the request.

**Comment by wbelk** [comment] 2024-02-13 16:55
I've debugged this as well. The Shopify admin is loading my app into three separate iframes, causing three requests to my index route each page reload

```
iframe[name="app-iframe"]
iframe[name="modal://content/classic"]
iframe[name="modal://content/max"]
```

To me this seems like a bug and inefficient, and makes my debugging much more difficult, what am I missing?

**Comment by trev0r** [comment] 2024-03-01 02:42
Same issue here as well

**Comment by wbelk** [comment] 2024-03-01 02:52
> Yea we got this same issue, the app sends request twice, the first is cancelled, ~but our server already processes the request.~ . Actually when the app is pin in the list, shopify will automatically send request to all apps as if user is actually visit them, making our server handle the same request twice.

Yes I noticed this as well. I have 5 apps. If I'm on my dev shop it can be a nightmare.

**Comment by henrytao-me** [comment] 2024-03-25 18:29
Hi all, there are serval related issues here. I would like to summarize as below:

- There is always a `CANCELED` request on first load => This is confirmed a bug and we are fixing it. It should be merged today or tomorrow. => This shouldn't affect your WebVitals score.
- There is a `prefetch=1` request when loading Admin => We are preloading top pinned apps in the background. However, it's turned off right now. => This shouldn't affect your WebVitals score. 
- There are two additionally iframe for modals => This is gone now on production and you shouldn't see it. We were preloading two modal iframe for each app. So that it loads the modal content faster without showing the spinner. => This might affect your WebVitals score depending on your server load. 

I will close this ticket once the `canceled` request is fixed.

**Closed** 2024-03-25 18:49 UTC
Labels: bug

**Comment by tutNichts** [comment] 2025-06-01 16:41
I'm facing the same issue as well.

@henrytao-me  — it would be great to get an official response on how this is intended to be addressed (hopefully without relying on a unique constraint at the database level as the primary solution).

@jason-engage  — any updates from your side on this (except adding the unique constraint)?

**Comment by yondean** [comment] 2025-06-19 06:57
If this is intentional, it would've been nice to have this mentioned somewhere in the docs. 

Two more issues relating to this:
- https://github.com/Shopify/shopify-app-template-remix/issues/1015
- https://github.com/Shopify/shopify-app-template-remix/issues/474

**Comment by ThorCStenbaek** [comment] 2025-06-23 08:57
Lmao, why is this closed?

**Comment by VerheeckeLorenzo** [comment] 2025-06-26 21:44
Seems to be magically resolved as of today 26/06? Can you guys check?
