### ISSUE TITLE
App Bridge APP::CART::UPDATE doesn't work for Android Shopify POS

### ISSUE THREAD

**Issue by derrickrc** [Shopify/shopify-app-bridge#75] opened 2021-09-01 22:24 UTC
Title says it all, the same snippet below works for iOS without issue: https://shopify.dev/apps/tools/app-bridge/actions/cart

```
var unsubscriber = cart.subscribe(Cart.Action.UPDATE, function (payload) {
  console.log('[Client] fetchCart', payload);
  unsubscriber();
});
cart.dispatch(Cart.Action.FETCH);
```

**Comment by andrewapperley** [comment] 2021-09-07 19:33
Hey @derrickrc Thanks for reporting this issue. I'm going to get this in front of the Retail team.

**Comment by BrittaEvansFenton** [comment] 2021-09-09 18:11
Hi @derrickrc I'm unable to reproduce this on my side, so I'm hoping I can gather a little more information from you:
1. Are you you getting any returns? or just errors?
2. What is the state of the cart at the time you are calling?
3. Where is your app located in POS? Are you trying to make the call on the Smart Grid?

**Comment by derrickrc** [comment] 2021-09-09 18:38
@BrittaEvansFenton thanks for looking into this. 

1. I don't believe I am getting any returns at all in this case (though it's impossible to say because Chrome WebView debugging no longer works with the "new" Android POS)
2. The state of the POS cart is that it has items in it already. It similarly just doesn't run at all if there are no items in the cart.
3. Yes, I am making the call as an embedded POS app on the Smart Grid

To confirm, you're able to get the payload callback with that snippet of code upon opening an embedded POS app? I am on a Pixel 4a on Shopify POS 4.16.0. 

For example, if I change the `console.log()` to `alert()` (to make sure I can see the `payload` value without WebView debugging), nothing happens.

**Comment by once2go** [comment] 2021-09-09 22:58
Hi @derrickrc 
When did you check WebView debugging last time? This feature should be fixed in last releases. 
I think, we need more information from your side to figure out what is wrong. 
Is it a first time you using this API? Are you able to modify the cart from your app (like add items, discounts, etc...)?

**Comment by derrickrc** [comment] 2021-09-09 23:14
@once2go Hi Denys, thanks for responding. 

WebView Debugging has not worked for me, or for any other developers (https://shopifypartners.slack.com/archives/C4E5GV5U4/p1628797121188300) since the "new" Android POS launched. I just tried it again, please see the screenshot - when I open my embedded app, it does not show up. 

This is not my first time using this API, I am using it in a production app. As mentioned, the code snippet works for iOS and it fetches the cart, but for Android Shopify POS the code does not execute and I am unable to get the cart payload. I am not sure what else I can share. 

![Screen Shot 2021-09-09 at 4 09 09 PM](https://user-images.githubusercontent.com/46724607/132774216-1111b2b2-ec22-492b-b015-a5261ba7450f.png)

**Comment by BrittaEvansFenton** [comment] 2021-09-10 21:04
Hey @derrickrc can we grab your email. We want to test your application if possible and ask a lot more questions.

**Comment by once2go** [comment] 2021-09-13 14:58
I tried to run @derrickrc store with mal build config and as you can see Webview debug works for me even build is not debuggable 
![image](https://user-images.githubusercontent.com/4435902/133107189-55976479-4ee0-4ad9-a6ff-824d4bed3ebf.png)

**Comment by gvarandas** [comment] 2021-10-04 16:30
Hey @derrickrc 👋 
We have shipped a fix in our latest version that corrected how the cart actions were handled in the App Bridge for POS Next Android. Can you please check if this issue has been fixed as well?

**Closed as completed** 2021-10-27 15:25 UTC
Labels: bug
