### ISSUE TITLE
CDN-hosted createApp(..) problem: host must be provided

### ISSUE THREAD

**Issue by skjolber** [Shopify/shopify-app-bridge#48] opened 2021-05-01 19:49 UTC
## Describe the bug
Unable to create app using the CDN-hosted version.

```
"{name: "AppBridgeError", message: "APP::ERROR::INVALID_CONFIG: host must be provided", action: undefined, type: "APP::ERROR::INVALID_CONFIG", stack: "AppBridgeError: APP::ERROR::INVALID_CONFIG: host must be provided"}"
```

### To Reproduce

```
var AppBridge = window['app-bridge'];
var createApp = AppBridge.default;

const app = createApp({
	apiKey: 'x',
	shopOrigin: 'y'
});
```
where `x` and `y`  is set accordingly. Adding a 'host' parameter fails with another message.

### Packages and versions

```
<script src="https://unpkg.com/@shopify/app-bridge@2"></script>
```
## Platform

Chrome (client side).

### Additional context

The documentation for CDN-based + javascript is confusing and fragmented.

**Comment by olegbek** [comment] 2021-05-07 10:12
I see the same in the console. The app is loading but this is definitely strange.

**Comment by skjolber** [comment] 2021-05-07 17:42
@andrewapperley & @iainmcampbell is this accurate?

**Comment by ozzyonfire** [comment] 2021-05-12 19:03
Having the same issue, but using the latest npm package

**Comment by richilton** [comment] 2021-05-13 15:33
Same issue here with npm package v2.0.0, v2.0.1 and v2.0.2. 

Changing the `shopOrigin` key to `host` causes this error instead:

```AppBridgeError: APP::ERROR::INVALID_CONFIG: not a valid host, please use the value provided by Shopify```

**Comment by richilton** [comment] 2021-05-13 16:11
After a bit more digging...

`node_modules/@shopify/app-bridge/client/Client.js` contains the following code (lines 167 to 169):

```
function decodeConfig(config) {
    var _a;
    return __assign(__assign({}, config), { host: atob((_a = config.host) === null || _a === void 0 ? void 0 : _a.replace(/_/g, '/').replace(/-/g, '+')) });
}
```

It appears to be testing that the `host` is a valid Base64 string, first replacing `_` and `-` with valid Base64 characters. But note that it does not replace `.`, which suggests that the `host` parameter should not be a full hostname - perhaps it should just be the myshopify.com subdomain?

I tried feeding it just the subdomain (e.g. `example` instead of `example.myshopify.com`) and the app loaded, but then other app-bridge-react components stopped working. I'm very new to the node/React/Polaris/App Bridge ecosystem, so don't know whether that is a related issue or caused by other bugs/breaking changes in v2.0.

In the meantime, I'm reverting to 1.30.0 until 2.0.2 can be fixed or properly documented.

**Comment by skjolber** [comment] 2021-05-15 14:21
Was able to add the host in the config as 

```
var host = window.btoa(shopifyDomain + '/admin');          
```

**Comment by MedElloumi** [comment] 2021-05-16 14:45
> Was able to add the host in the config as
> 
> ```
> var host = window.btoa(shopifyDomain + '/admin');          
> ```

Adding /admin solved my problem ... being redirected to the wrong address after OAUTH ... this must be added to the documentation.

**Comment by kinngh** [comment] 2021-05-18 06:56
Update your `pages/_app.js` to include `host` in `getInitialProps` and then call it in your `config` from `this.props` along side `shopOrigin`

```javascript
const { Component, pageProps, shopOrigin, host } = this.props;
const config = { apiKey: API_KEY, shopOrigin, host, forceRedirect: true };
...
...
...

MyApp.getInitialProps = async ({ ctx }) => {
  return { shopOrigin: ctx.query.shop, host: ctx.query.host };
};
```

And if you're using something like recurring subscriptions, you'll need to get host from the URL and pass it in your return URL

```javascript
const getHost = (ctx) => {
 const baseUrl = new URL(`https://${ctx.request.header.host}${ctx.request.url}`);
  return baseUrl.searchParams.get("host");  
 };
server.use(
 createShopifyAuth({ async afterAuth(ctx) {
  const { shop, scope, accessToken } = ctx.state.shopify;
  const host = getHost(ctx);
  ACTIVE_SHOPIFY_SHOPS[shop] = scope;
  const returnUrl = `https://${Shopify.Context.HOST_NAME}?host=${host}&shop=${shop}`;
  const subscriptionUrl = await getSubscriptionUrl(accessToken, shop, returnUrl );
  ctx.redirect(subscriptionUrl);
  },
 })
);
```

**Comment by dthpth** [comment] 2021-06-04 19:41
faced the same issue after another `yarn upgrade`

adding `'/admin'` did the thing, but I found that curious:
https://www.npmjs.com/package/@shopify/app-bridge-react#readme
```js
const app = createApp({
  apiKey: 'API key from Shopify Partner Dashboard',
  host: 'host from URL search parameter',
});
```
thus if you run your app inside an iframe in Shopify admin, you should take `host` from the requested URL, and `shopOrigin` is no longer needed(?)

Did the Documentation outdated? https://shopify.dev/tools/app-bridge/react-components#getting-started

**Comment by jaredbeck** [comment] 2021-08-02 17:15
Another idea we are considering:

> The Shopify admin provides the host parameter as part of the app URL when loading your embedded app:
> https://shopify.dev/apps/tools/app-bridge/migrating

For example,

```
const shopifyHost = (new URL(window.location)).searchParams.get('host');
```

**Comment by tobymurray** [comment] 2021-09-10 21:44
I ran into this as well using app-bridge version 2. From my understanding: when you launch an embedded app from within the Shopify admin, you're expected to go through the OAuth flow. During OAuth, both the configured App URL and "callback" URL get HTTP GET requests from Shopify that contain a base 64 encoded host query string parameter. E.g. I have configured `/auth/install` as my App URL, so I see an HTTP GET that looks like (broken onto newlines for readability):

```
/auth/install?
	hmac=37fb736c3955696f36377647f9588d764a564447430b96847f161b5f6ef3d552
	&host=dGhpcy1pcy1ub3QtcmVhbC5teXNob3BpZnkuY29tL2FkbWlu
	&locale=en
	&session=465ce117c958118babb277f53087c52382475461d2a48262af3acdd81f3faef5
	&shop=this-is-not-real.myshopify.com
	&timestamp=1631309172
```

This includes the `host` query string parameter: `dGhpcy1pcy1ub3QtcmVhbC5teXNob3BpZnkuY29tL2FkbWlu` 
which decodes to the above mentioned form `this-is-not-real.myshopify.com/admin`.

Invoking createApp then succeeds with:
```
var app = AppBridge.createApp({
    apiKey: "7e790b92bb28417b96bf3cb0bfe087e1", // Your app's API key (not the secret)
    host: "dGhpcy1pcy1ub3QtcmVhbC5teXNob3BpZnkuY29tL2FkbWlu" // the host query parameter from the OAuth requests
});
```

This is documented in a linked page, https://shopify.dev/apps/tools/app-bridge/retrieve-the-host although it's a bit off the beaten path for such a crucial aspect.

**Comment by charlesdobson** [comment] 2024-03-06 22:06
Closing as outdated, but please reopen if needed.

The new App Bridge offers a much easier configuration. All you have to do is provide the `apiKey` to the script tag. Check out the docs [here](https://shopify.dev/docs/api/app-bridge-library#getting-started)!

**Closed by charlesdobson** 2024-03-06 22:06 UTC
Labels: bug
