### ISSUE TITLE
APP::ERROR::INVALID_ORIGIN

### ISSUE THREAD

**Issue by catalogplus** [Shopify/shopify-app-bridge#103] opened 2022-04-04 11:03 UTC
## Describe the bug

I get this error from the app bridge, but have no idea why.

### To Reproduce

Steps to reproduce the behaviour:

1. Load an already installed shopify public app

### Expected behaviour

No error.

### Packages and versions

List the relevant packages you’re using, and their versions. For example:

    "@shopify/app-bridge-react": "^2.0.8",
    "@shopify/app-bridge-utils": "^2.0.10",

## Platform

- OS:  MacOS
- OS Version: 10.15.7
- App: public web app on desktop

### Additional context

I have an react app created with CRA, using Axios for communication with the backend. The backend is written in Golang.
There is a ngrok tunnel exposing the front-end, and another tunnel exposing the backend.

**Comment by catalogplus** [comment] 2022-04-05 16:35
Hey @joeyfreund, this used to work, but it's in development so I may have changed something on my end since it worked.

**Comment by catalogplus** [comment] 2022-04-05 19:07
I think I have an idea why it may be failing. Unlike the sample app created with the Shopify CLI tool, which has the server and client being served from the same domain, my client and server are each on their own URL. So perhaps that's causing the issue?

**Comment by dev-prakhar** [comment] 2022-05-10 16:37
Hey Team. 

I am also facing the same issue. I think this is pretty common use case where we want to serve our backend from a different domain and client from a different domain. 

I think embedded apps expects server and client to be on the same domain. Is there a way we could have our backend server and client hosted on different domains and still be able to work with embedded apps?

**Comment by henrytao-me** [comment] 2022-05-12 15:51
@marisveide @dev-prakhar Can you share your app here that I can test? If not, you can ping me on [Shopify Partners Slack](shopifypartners.slack.com)

**Comment by henrytao-me** [comment] 2022-05-13 21:51
PR is coming. We will ship it next week. Thanks for reporting this bug 🙇

**Comment by henrytao-me** [comment] 2022-05-17 14:53
The fix is merged. This is the step to reproduce

- Open any sale channel so that the auth flow is finished
- Open the test app from apps list
- Now, open that sale channel again from the sidenav. Verify that sale channel is opened fine
- Use browser back history to back 1 stack. Expect to see the test app should work fine. It previously shows invalid origin

**Closed by henrytao-me** 2022-05-17 14:53 UTC
Labels: bug

**Comment by henrytao-me** [comment] 2023-01-09 20:07
Hi @mwrigley, you can still have client and server are on different domain but you need to make sure the application url domain in partner account is your client domain, not the server domain.

**Comment by mwrigley** [comment] 2023-01-09 20:39
> I think I have an idea why it may be failing. Unlike the sample app created with the Shopify CLI tool, which has the server and client being served from the same domain, my client and server are each on their own URLs. Also embedded in this error is a message: "Message origin 'https://client.ngrok.io' does not match app origin 'https://server.loophole.site'."
> 
> But in the app settings there is just one value for the app URL, which is the server URL which is where the installation flow starts.

I thought the original poster had the server in the app url setting as well. So this is not possible? I have to start the app from the client

**Comment by mwrigley** [comment] 2023-01-09 20:57
Okay. Thanks for the quick response

**Comment by paven-c** [comment] 2023-06-15 15:15
Hi Team. I created an embedded app. First, I configured the backend URL as the app URL. Until I found APP::ERROR::INVALID_ORIGIN Error, I configured the front-end URL as the app URL. After clicking Install the application, I went directly to the page where the application is embedded, like https://admin.shopify.com/store/xxx/apps/3213412dwewc9f5cf0e8d9dca6e14, but the page prompt 404
There is no page at this address, and there is no iframe element in the inspect page.

**Comment by prashant-chai** [comment] 2023-07-21 05:41
Hi, @paven-c @henrytao-me @therealtgd 

Any way to fix this scenario as this is pretty common, we too have our frontend and backend app on different origins, when opening the app it opens in a new tab with the `admin.shopify.com` origin, and then it automatically opens a new tab with old *.myshopify.com domain.

I think it is because we have set up our backend URL as the app URL, we too get this AppBridge error in the console saying the message origin doesn't match the app origin

**Comment by iam7seven7** [comment] 2023-07-30 15:01
> Hey, I have the same problem. The app URL in App Settings is the URL of my backend server which is where the installation and auth flow starts. Am I forced to change that app URL in App Settings to the client URL? If so, how would I start the installation flow there?

I workarounded it by url redirection:

1. App Settings app URL: `https://<your frontend base url>/install.html`
2. Create `install.html` in frontend app: 
Its only function is to redirect to backend `/install` endpoint immediately
```
<html>
  <head>
    <script type="module">
        window.location.href = `https:://<your backend base url>/install${window.location.search}`;
      }
    </script>
  </head>
</html>
```
3. Create `/install` endpoint in backend expressjs app:
Execute `shopify.ensureInstalledOnShop()` and redirect to frontend React app root.
```
app.get("/install", shopify.ensureInstalledOnShop(), async (_req, res) => {
  return res.redirect(`https://<your frontend base url>${_req._parsedUrl.search}`);
});
```
